### PR TITLE
Add packaging for Meteor.js, http://meteor.com

### PR DESCRIPTION
**Pull request by dandv**
Hi David,

I'm a Meteor.js dev and volunteer package maintainer for [Meteor](http://meteor.com). Isotope is a great layout library, and adding it to Meteor's ecosystem will expose it to many new devs (Meteor has 20k+ stars on GitHub), likely bringing in new testers and contributors.

This PR will let you directly publish updated versions of the library as they become available. All you have to do is create an account at https://meteor.com/ (click *SIGN IN*, then *Create account*). After you've done that, please let me know the name of the account, and I'll add you as a maintainer.

I've already published the current version of the package on [Atmosphere](https://atmospherejs.com/isotope/isotope) (Meteor's package directory). When you release new versions, you'll be able to publish them to Atmosphere by running

    grunt meteor

Thanks & best regards,
Dan, [official Meteor integrations team](https://github.com/raix/Meteor-community-discussions/issues/14)

### CODE REVIEW

**Comment by silverbuggy** [comment]
+1

**Comment by superbilk** [comment]
+1

**Comment by lagden** [comment]
+1

**Comment by rdibona** [comment]
+1

**Comment by coffeedoughnuts** [comment]
+1 and also worth mentioning that as of now, the current package on atmosphere is at 1,780 installs

**Comment by cmaddalozzo** [comment]
+1

**Comment by dcworldwide** [comment]
+1

**Comment by Vheissu** [comment]
+1

**Comment by timneutkens** [comment]
@dandv @desandro this pull request can be closed in favor of npm support in Meteor right?

**Comment by dandv** [comment]
Correct.

**Pull request closed without merging**
