### PR TITLE
Added logic to process equal height

### PR DESCRIPTION
**Pull request by duckzland**
Adding logic to process equal height for fitRows, tested only with normal layouting, some glitch in ajax fetched content + appended, need testing when filtering applied

### CODE REVIEW

**Comment by duckzland** [comment]
initial attempt to add equal height to fitrows, need testing when filtering applied

**Comment by desandro** [comment]
Thanks for taking a shot at this. I'll leave this open for a bit for others to note.

**Comment by stephandesouza** [comment]
:+1: 

Good jog.

**Comment by joeworkman** [comment]
Any status on getting this merged in?

**Comment by Vheissu** [comment]
Tested this and works well. Can we merge it please? I think this is a great change to have in the library.

**Comment by medoingthings** [comment]
Would be awesome, if this could be merged. Great extension to the library and currently needed :)
Any ETA on this?

**Comment by HarshilShah** [comment]
It’s been a while, so any updates on this? Would be awesome to have, really.

**Comment by desandro** [comment]
I have decided not to merge this PR. This is a neat feature, but it works against Isotope logic flow. Isotope doesn't have a hook for multiple iteration passes over its items, which is required for this behavior. Which means this feature is likely to conflict with others.

**Pull request closed without merging**
