### PR TITLE
Update masonry.js

### PR DESCRIPTION
**Pull request by hpphat92**

### CODE REVIEW

**Comment by desandro** [comment]
This is a weird issue. If you install Masonry via Bower, the package is `masonry`, but if you install it via npm, the package is `masonry-layout`. I've kept the AMD definition with `masonry` for the RequireJS + Bower combo, which I use to build Metafizzy's `pkgd` files. I'll keep this PR open for a bit for discussion.

**Comment by ilyaashapatov** [comment]
yes, this problem define npm
script search into masonry, when folder name masonry-layout. It's bug

**Comment by kevinlin505** [comment]
@desandro will this get merge anytime soon? I am getting this error while using yarn.
`ERROR in ./~/isotope-layout/js/layout-modes/masonry.js
Module not found: Error: Can't resolve 'masonry/masonry'`

**Comment by zArubaru** [comment]
Just ran in to this problem too, and btw just `'masonry-layout'` works too, doesn't seem need the `masonry-layout/masonry`. Maybe there could be an additional check here, and then insert the correct one as needed?

**Comment by hahnmg** [comment]
Ran into this today aswell. Could not fix it with https://isotope.metafizzy.co/extras.html#webpack or any other solution found on here. Only renaming as in https://github.com/metafizzy/isotope/pull/1248/commits/a76348785fe753fdfae9497b748c4ace5a96108a works.

**Comment by desandro** [comment]
This fix was added in v3.0.5,  SHA# 65a03da9380b9304ffb3871ebb25aed7e62cc7f1. Along with changing the package name to `isotope-layout` for consistency.

Thanks again for your contribution! 🌈🐻

**Pull request closed without merging**
